    - name: install apache2
      apt: name=apache2 state=latest update_cache=yes

    - name: ensure apache is running (and enable it at boot)
      service: name=apache2 state=started enabled=yes


    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: enabled mod_macro
      apache2_module: name=macro state=present
      notify:
        - restart apache2

    - name: Copy macro.conf
      copy: src=files/macro.conf dest={{apache_dir}}/mods-available/macro.conf

    - name: Symbol link macro.conf
      file: src=/{{apache_dir}}/mods-available/macro.conf dest={{apache_dir}}/mods-enabled/macro.conf state=link
      notify:
        - restart apache2

    - name: enabled mod_headers
      apache2_module: name=headers state=present
      notify:
        - restart apache2

    - name: Copy security.conf
      copy: src=files/security.conf dest={{apache_dir}}/conf-available/security.conf

    - name: Symbol link security.conf
      file: src={{apache_dir}}/conf-available/security.conf dest={{apache_dir}}/conf-enabled/security.conf state=link
      notify:
        - restart apache2

    - name: Change permission default directory
      file: path={{DEFAULT_DIR}} owner={{USER}} group={{USER}} mode=0755 state=directory

    - name: Copy template Apache ports.conf
      template: src=templates/ports.conf.j2 dest={{apache_dir}}/ports.conf mode=0644

    - name: Copy template Apache vhost
      template: src=templates/vhost.conf.j2 dest={{apache_dir}}/sites-available/vhost.conf mode=0644

    - name: Copy template Apache vhost-default
      template: src=templates/000-default.conf.j2 dest={{apache_dir}}/sites-available/000-default.conf.j2 mode=0644
      notify:
        - restart apache2


    - name: Symbol link vhost.conf
      file: src={{apache_dir}}/sites-available/vhost.conf dest={{apache_dir}}/sites-enabled/vhost.conf state=link
      notify:
        - restart apache2

