- name: Add repo java8
  become: yes
  apt_repository: repo='ppa:webupd8team/java'
  tags: java

- name: Apt_key add
  apt_key: keyserver="keyserver.ubuntu.com" id=EEA14886
  tags: java

- name: accept java 8 license
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags: java  

- name: install java 8
  become: yes
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default   
    - ttf-mscorefonts-installer
  tags: java

