- name: Add repositories base
  become: yes
  apt_repository: repo="{{item}}" state=present
  with_items:
       - 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
       - 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
  tags: java

- name: Apt_key add
  apt_key: keyserver="keyserver.ubuntu.com" id=EEA14886
  tags: java


- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags: java  

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default   
    - ttf-mscorefonts-installer
  tags: java

- name: Copy fonts files to Java Home
  copy: src={{item}} dest={{java_home}}/jre/lib/fonts/
  with_fileglob: /usr/share/fonts/truetype/msttcorefonts/*
  tags: java
