- name: Install list of packages
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    force: yes
    allow_unauthenticated: yes
  with_items: 
    - curl
    - software-properties-common
  tags: base
