- name: Deploy java-chef-test.war
  unarchive: src={{ warRemotePath }}/{{ warName }} dest=/var/lib/tomcat8/webapps/ROOT/ copy=no mode=0755 owner=tomcat8 group=tomcat8
  notify:
      - restart tomcat8

- name: Validate deploy
  uri: 
    url: http://localhost:8080/java-chef-test/chef/ping
    method: GET
    return_content: yes
  register: result
  until: result.content("Hello Chef deployed war") != -1
  retries: 2
  delay: 5