- name: Deploy java-chef-test.war
  unarchive: src={{ warRemotePath }}/{{ warName }} dest=/var/lib/tomcat8/webapps/ROOT/ copy=no mode=0755 owner=tomcat8 group=tomcat8
  notify:
      - restart tomcat8

- name: Validate deploy
  shell: curl --head --silent  http://localhost:8080/java-chef-test/chef/ping
  register: result
  until: result.stdout.find("Hello Chef deployed war") != -1
  retries: 2
  delay: 5


handlers:
  - name: Restart tomcat8
    service: name=tomcat8 state=restarted


vars:
  warRemotePath: "{{ /home/avenuecode/devops-challenge-ac002/cfg-management/assets }}"
  warName: {{ java-chef-test.war }}
